CREATE TABLE [dbo].[CF] (
    [CID] INT NOT NULL,
    [FID] INT NOT NULL,
    CONSTRAINT [PK_CF] PRIMARY KEY CLUSTERED ([CID] ASC, [FID] ASC),
    CONSTRAINT [FK_CF_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_CF_GID] FOREIGN KEY ([FID]) REFERENCES [dbo].[Forum] ([FID])
);

