CREATE TABLE [dbo].[CG] (
    [CID] INT NOT NULL,
    [GID] INT NOT NULL,
    [ID]  INT NULL,
    CONSTRAINT [PK_CG] PRIMARY KEY CLUSTERED ([CID] ASC, [GID] ASC),
    CONSTRAINT [FK_CG_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_CG_GID] FOREIGN KEY ([GID]) REFERENCES [dbo].[Groups] ([GID])
);

