CREATE TABLE [dbo].[CJS] (
    [CID]  INT NOT NULL,
    [JSID] INT NOT NULL,
    CONSTRAINT [PK_CJS] PRIMARY KEY CLUSTERED ([CID] ASC, [JSID] ASC),
    CONSTRAINT [FK_CJS_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_CJS_JSID] FOREIGN KEY ([JSID]) REFERENCES [dbo].[JudgeSolve] ([JSID])
);

