CREATE TABLE [dbo].[CN] (
    [CID]  INT NOT NULL,
    [NID]  INT NOT NULL,
    [Rank] INT NULL,
    CONSTRAINT [PK_CN] PRIMARY KEY CLUSTERED ([CID] ASC, [NID] ASC),
    CONSTRAINT [FK_CN_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_CN_NID] FOREIGN KEY ([NID]) REFERENCES [dbo].[Note] ([NID])
);



