CREATE TABLE [dbo].[ContentType] (
    [CTID]  SMALLINT       IDENTITY (1, 1) NOT NULL,
    [Title] VARCHAR (100)  NOT NULL,
    [Des]   NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_ContentType_CTID] PRIMARY KEY CLUSTERED ([CTID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [UQ_ContentType_Title] UNIQUE NONCLUSTERED ([Title] ASC) WITH (FILLFACTOR = 80)
);



