CREATE TABLE [dbo].[CT] (
    [CID]  INT NOT NULL,
    [TID]  INT NOT NULL,
    [Rank] INT NULL,
    CONSTRAINT [PK_CT] PRIMARY KEY CLUSTERED ([CID] ASC, [TID] ASC),
    CONSTRAINT [FK_CT_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_CT_tID] FOREIGN KEY ([TID]) REFERENCES [dbo].[Tag] ([TID])
);

