CREATE TABLE [dbo].[CTC] (
    [CID]  INT NOT NULL,
    [TCID] INT NOT NULL,
    [Rank] INT NULL,
    CONSTRAINT [PK_CTC] PRIMARY KEY CLUSTERED ([CID] ASC, [TCID] ASC),
    CONSTRAINT [FK_CTC_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_CTC_TCID] FOREIGN KEY ([TCID]) REFERENCES [dbo].[TestCase] ([TCID])
);



