CREATE TABLE [dbo].[CText] (
    [CTID] INT            IDENTITY (1, 1) NOT NULL,
    [Text] NVARCHAR (MAX) NULL,
    [MD5]  NVARCHAR (32)  NOT NULL,
    CONSTRAINT [PK_CText_CTID] PRIMARY KEY CLUSTERED ([CTID] ASC),
    CONSTRAINT [UQ_CText_MD5] UNIQUE NONCLUSTERED ([MD5] ASC)
);





