CREATE TABLE [dbo].[ForumRel] (
    [FID1] INT NOT NULL,
    [FID2] INT NOT NULL,
    CONSTRAINT [PK_ForumRel] PRIMARY KEY CLUSTERED ([FID1] ASC, [FID2] ASC),
    CONSTRAINT [FK_ForumRel_FID1] FOREIGN KEY ([FID1]) REFERENCES [dbo].[Forum] ([FID]),
    CONSTRAINT [FK_ForumRel_FID2] FOREIGN KEY ([FID2]) REFERENCES [dbo].[Forum] ([FID])
);

