CREATE TABLE [dbo].[FT] (
    [FID]  INT NOT NULL,
    [TID]  INT NOT NULL,
    [Rank] INT NULL,
    CONSTRAINT [PK_FT] PRIMARY KEY CLUSTERED ([FID] ASC, [TID] ASC),
    CONSTRAINT [FK_FT_FID] FOREIGN KEY ([FID]) REFERENCES [dbo].[Forum] ([FID]),
    CONSTRAINT [FK_FT_TID] FOREIGN KEY ([TID]) REFERENCES [dbo].[Tag] ([TID])
);

