CREATE TABLE [dbo].[GC] (
    [GID] INT NOT NULL,
    [CID] INT NOT NULL,
    [ID]  INT NULL,
    CONSTRAINT [PK_GC] PRIMARY KEY CLUSTERED ([GID] ASC, [CID] ASC),
    CONSTRAINT [FK_GC_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_GC_GID] FOREIGN KEY ([GID]) REFERENCES [dbo].[Groups] ([GID])
);

