CREATE TABLE [dbo].[NC] (
    [NID]  INT NOT NULL,
    [CID]  INT NOT NULL,
    [Rank] INT NULL,
    CONSTRAINT [PK_NC] PRIMARY KEY CLUSTERED ([NID] ASC, [CID] ASC),
    CONSTRAINT [FK_NC_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_NC_NID] FOREIGN KEY ([NID]) REFERENCES [dbo].[Note] ([NID])
);



