CREATE TABLE [dbo].[NText] (
    [NTID]   INT            IDENTITY (1, 1) NOT NULL,
    [Text]   NVARCHAR (MAX) NULL,
    [MD5]    NVARCHAR (32)  NOT NULL,
    [Length] INT            NULL,
    CONSTRAINT [PK_NText_NTID] PRIMARY KEY CLUSTERED ([NTID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [UQ_NText_MD5] UNIQUE NONCLUSTERED ([MD5] ASC) WITH (FILLFACTOR = 80)
);



