CREATE TABLE [dbo].[OCT] (
    [OID]  INT      NOT NULL,
    [CTID] SMALLINT NOT NULL,
    CONSTRAINT [PK_OCT] PRIMARY KEY CLUSTERED ([OID] ASC, [CTID] ASC),
    CONSTRAINT [FK_OCT_CTID] FOREIGN KEY ([CTID]) REFERENCES [dbo].[ContentType] ([CTID]),
    CONSTRAINT [FK_OCT_OID] FOREIGN KEY ([OID]) REFERENCES [dbo].[Object] ([OID])
);

