CREATE TABLE [dbo].[RO] (
    [RID] INT NOT NULL,
    [OID] INT NOT NULL,
    CONSTRAINT [PK_RO] PRIMARY KEY CLUSTERED ([RID] ASC, [OID] ASC),
    CONSTRAINT [FK_Report_OID] FOREIGN KEY ([OID]) REFERENCES [dbo].[Object] ([OID]),
    CONSTRAINT [FK_Report_RID] FOREIGN KEY ([RID]) REFERENCES [dbo].[Report] ([RID])
);

