CREATE TABLE [dbo].[TC] (
    [TID] INT NOT NULL,
    [CID] INT NOT NULL,
    CONSTRAINT [PK_TC] PRIMARY KEY CLUSTERED ([TID] ASC, [CID] ASC),
    CONSTRAINT [FK_TC_CID] FOREIGN KEY ([CID]) REFERENCES [dbo].[Class] ([CID]),
    CONSTRAINT [FK_TC_tID] FOREIGN KEY ([TID]) REFERENCES [dbo].[Tag] ([TID])
);

