CREATE TABLE [dbo].[Text] (
    [TID]  INT            IDENTITY (1, 1) NOT NULL,
    [Text] NVARCHAR (MAX) NULL,
    [MD5]  NVARCHAR (32)  NOT NULL,
    CONSTRAINT [PK_Text_TID] PRIMARY KEY CLUSTERED ([TID] ASC),
    CONSTRAINT [UQ_Text_MD5] UNIQUE NONCLUSTERED ([MD5] ASC)
);

