CREATE TABLE [dbo].[TF] (
    [TID]  INT NOT NULL,
    [FID]  INT NOT NULL,
    [Rank] INT NULL,
    CONSTRAINT [PK_TF] PRIMARY KEY CLUSTERED ([TID] ASC, [FID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_TF_FID] FOREIGN KEY ([FID]) REFERENCES [dbo].[Forum] ([FID]),
    CONSTRAINT [FK_TF_TID] FOREIGN KEY ([TID]) REFERENCES [dbo].[Tag] ([TID])
);



