CREATE TABLE [dbo].[UUID2PublicSP] (
    [UUID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [SPName] NVARCHAR (255)   NOT NULL,
    CONSTRAINT [PK_UUID2PublicSP] PRIMARY KEY CLUSTERED ([UUID] ASC),
    CONSTRAINT [UQ_UUID2PublicSP_SPName] UNIQUE NONCLUSTERED ([SPName] ASC)
);

